# Generated by Django 3.2.7 on 2021-09-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('web_address', models.CharField(blank=True, max_length=100, null=True)),
                ('startup_pitch', models.CharField(max_length=1400)),
                ('startup_stage', models.CharField(max_length=100)),
                ('start_month', models.CharField(max_length=100)),
                ('start_year', models.CharField(blank=True, max_length=100, null=True)),
                ('incorporation', models.BooleanField(default=False)),
                ('county', models.CharField(max_length=100)),
                ('applicant_title', models.CharField(max_length=100)),
                ('applicant_first_name', models.CharField(max_length=100)),
                ('applicant_last_name', models.CharField(max_length=100)),
                ('applicant_email', models.CharField(max_length=100)),
                ('applicant_phone_no', models.CharField(max_length=100)),
                ('linkedin_account', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant_bio', models.CharField(max_length=140)),
                ('startup_elevator_pitch', models.CharField(max_length=140)),
                ('motivation', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
