# Generated by Django 3.2.7 on 2021-09-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startup',
            name='decline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startup',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
