# Generated by Django 3.2.7 on 2021-09-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210921_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='approve',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='decline',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='pending',
        ),
        migrations.AddField(
            model_name='startup',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_phone_no',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='startup',
            name='motivation',
            field=models.CharField(max_length=140),
        ),
    ]
