# Generated by Django 3.2.7 on 2021-09-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210922_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Approved', 'Approved')], max_length=100, null=True),
        ),
    ]
