# Generated by Django 3.2.7 on 2021-09-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_startup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='applicant_phone_no',
            field=models.CharField(max_length=13),
        ),
    ]
