# Generated by Django 3.2.7 on 2021-09-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_startup_applicant_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='applicant_title',
            field=models.CharField(choices=[('employee', 'Employee'), ('founder', 'Founder'), ('co-founder', 'Co-founder')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_month',
            field=models.CharField(choices=[('March', 'March'), ('October', 'October'), ('September', 'September'), ('February', 'February'), ('May', 'May'), ('July', 'July'), ('April', 'April'), ('January', 'January'), ('November', 'November'), ('June', 'June'), ('December', 'December'), ('August', 'August')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_year',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2021', '2021')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_stage',
            field=models.CharField(choices=[('prototype', 'Prototype'), ('users', 'Users'), ('paying users', 'Paying Users'), ('idea', 'Idea')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
