# Generated by Django 3.2.7 on 2021-09-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210923_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_type', models.CharField(choices=[('Angel Investor', 'Angel Investor'), ('Venture Capitalist', 'Venture Capitalist'), ('Other', 'Other')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('linkedin_address', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('employment_status', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.CharField(max_length=300)),
                ('experience', models.CharField(max_length=300)),
                ('reason', models.CharField(max_length=300)),
                ('application_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Declined', 'Declined')], default='Pending', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_title',
            field=models.CharField(choices=[('co-founder', 'Co-founder'), ('founder', 'Founder'), ('employee', 'Employee')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_month',
            field=models.CharField(choices=[('July', 'July'), ('September', 'September'), ('April', 'April'), ('June', 'June'), ('August', 'August'), ('January', 'January'), ('October', 'October'), ('February', 'February'), ('November', 'November'), ('December', 'December'), ('May', 'May'), ('March', 'March')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_year',
            field=models.CharField(blank=True, choices=[('2019', '2019'), ('2021', '2021'), ('2020', '2020'), ('2018', '2018')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_stage',
            field=models.CharField(choices=[('idea', 'Idea'), ('prototype', 'Prototype'), ('paying users', 'Paying Users'), ('users', 'Users')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Declined', 'Declined')], default='Pending', max_length=100),
        ),
    ]
