# Generated by Django 3.2.7 on 2021-09-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210926_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(choices=[('Admin', 'Admin')], max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_type',
            field=models.CharField(choices=[('Angel Investor', 'Angel Investor'), ('Venture Capitalist', 'Venture Capitalist'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='investor',
            name='status',
            field=models.CharField(choices=[('Declined', 'Declined'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_title',
            field=models.CharField(choices=[('co-founder', 'Co-founder'), ('employee', 'Employee'), ('founder', 'Founder')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_month',
            field=models.CharField(choices=[('May', 'May'), ('October', 'October'), ('March', 'March'), ('August', 'August'), ('April', 'April'), ('December', 'December'), ('February', 'February'), ('September', 'September'), ('June', 'June'), ('November', 'November'), ('July', 'July'), ('January', 'January')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_year',
            field=models.CharField(blank=True, choices=[('2018', '2018'), ('2020', '2020'), ('2021', '2021'), ('2019', '2019')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_stage',
            field=models.CharField(choices=[('paying users', 'Paying Users'), ('users', 'Users'), ('idea', 'Idea'), ('prototype', 'Prototype')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[('Declined', 'Declined'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
