# Generated by Django 3.2.7 on 2021-09-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210927_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='applicant_title',
        ),
        migrations.AddField(
            model_name='startup',
            name='applicant_role',
            field=models.CharField(choices=[('founder', 'Founder'), ('co-founder', 'Co-founder'), ('employee', 'Employee')], default='Founder', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_type',
            field=models.CharField(choices=[('Angel Investor', 'Angel Investor'), ('Venture Capitalist', 'Venture Capitalist'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_month',
            field=models.CharField(choices=[('June', 'June'), ('November', 'November'), ('February', 'February'), ('December', 'December'), ('October', 'October'), ('May', 'May'), ('July', 'July'), ('March', 'March'), ('April', 'April'), ('September', 'September'), ('January', 'January'), ('August', 'August')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_year',
            field=models.CharField(blank=True, choices=[('2018', '2018'), ('2020', '2020'), ('2019', '2019'), ('2021', '2021')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_stage',
            field=models.CharField(choices=[('paying users', 'Paying Users'), ('users', 'Users'), ('idea', 'Idea'), ('prototype', 'Prototype')], max_length=100),
        ),
    ]
