# Generated by Django 3.2.7 on 2021-09-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210927_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='applicant_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_type',
            field=models.CharField(choices=[('Venture Capitalist', 'Venture Capitalist'), ('Other', 'Other'), ('Angel Investor', 'Angel Investor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='investor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Approved', 'Approved')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_role',
            field=models.CharField(choices=[('founder', 'Founder'), ('employee', 'Employee'), ('co-founder', 'Co-founder')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_month',
            field=models.CharField(choices=[('February', 'February'), ('April', 'April'), ('May', 'May'), ('July', 'July'), ('August', 'August'), ('October', 'October'), ('January', 'January'), ('September', 'September'), ('March', 'March'), ('November', 'November'), ('December', 'December'), ('June', 'June')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2019', '2019'), ('2020', '2020'), ('2018', '2018')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_stage',
            field=models.CharField(choices=[('prototype', 'Prototype'), ('paying users', 'Paying Users'), ('users', 'Users'), ('idea', 'Idea')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Approved', 'Approved')], default='Pending', max_length=100),
        ),
    ]
