# Generated by Django 3.2.7 on 2021-09-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210927_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='county',
        ),
        migrations.AddField(
            model_name='startup',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_type',
            field=models.CharField(choices=[('Venture Capitalist', 'Venture Capitalist'), ('Other', 'Other'), ('Angel Investor', 'Angel Investor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='investor',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Declined', 'Declined')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_role',
            field=models.CharField(choices=[('employee', 'Employee'), ('co-founder', 'Co-founder'), ('founder', 'Founder')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_month',
            field=models.CharField(choices=[('June', 'June'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('January', 'January'), ('November', 'November'), ('July', 'July'), ('December', 'December'), ('May', 'May')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_stage',
            field=models.CharField(choices=[('idea', 'Idea'), ('prototype', 'Prototype'), ('paying users', 'Paying Users'), ('users', 'Users')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Declined', 'Declined')], default='Pending', max_length=100),
        ),
    ]
