# Generated by Django 3.2.7 on 2021-09-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210928_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='investor_type',
            field=models.CharField(choices=[('Angel Investor', 'Angel Investor'), ('Venture Capitalist', 'Venture Capitalist'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='investor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Approved', 'Approved')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_role',
            field=models.CharField(choices=[('co-founder', 'Co-founder'), ('founder', 'Founder'), ('employee', 'Employee')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_month',
            field=models.CharField(choices=[('February', 'February'), ('November', 'November'), ('June', 'June'), ('July', 'July'), ('May', 'May'), ('October', 'October'), ('April', 'April'), ('January', 'January'), ('December', 'December'), ('September', 'September'), ('August', 'August'), ('March', 'March')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_year',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2009', '2009'), ('2012', '2012'), ('2011', '2011'), ('2008', '2008'), ('2003', '2003'), ('2017', '2017'), ('2015', '2015'), ('2019', '2019'), ('2005', '2005'), ('2004', '2004'), ('2010', '2010'), ('2007', '2007'), ('2013', '2013'), ('2021', '2021'), ('2018', '2018'), ('2014', '2014'), ('2016', '2016'), ('2006', '2006')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_stage',
            field=models.CharField(choices=[('prototype', 'Prototype'), ('idea', 'Idea'), ('users', 'Users'), ('paying users', 'Paying Users')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Approved', 'Approved')], default='Pending', max_length=100),
        ),
    ]
