# Generated by Django 3.2.7 on 2021-09-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210929_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='investor_type',
            field=models.CharField(choices=[('Other', 'Other'), ('Venture Capitalist', 'Venture Capitalist'), ('Angel Investor', 'Angel Investor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='investor',
            name='status',
            field=models.CharField(choices=[('Declined', 'Declined'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_phone_no',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_role',
            field=models.CharField(choices=[('employee', 'Employee'), ('co-founder', 'Co-founder'), ('founder', 'Founder')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_month',
            field=models.CharField(choices=[('February', 'February'), ('November', 'November'), ('October', 'October'), ('December', 'December'), ('January', 'January'), ('July', 'July'), ('August', 'August'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('September', 'September'), ('June', 'June')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_year',
            field=models.CharField(blank=True, choices=[('2012', '2012'), ('2019', '2019'), ('2020', '2020'), ('2015', '2015'), ('2008', '2008'), ('2005', '2005'), ('2009', '2009'), ('2007', '2007'), ('2013', '2013'), ('2006', '2006'), ('2014', '2014'), ('2018', '2018'), ('2010', '2010'), ('2021', '2021'), ('2003', '2003'), ('2011', '2011'), ('2016', '2016'), ('2004', '2004'), ('2017', '2017')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_stage',
            field=models.CharField(choices=[('users', 'Users'), ('idea', 'Idea'), ('prototype', 'Prototype'), ('paying users', 'Paying Users')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[('Declined', 'Declined'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
