# Generated by Django 3.2.7 on 2021-10-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210929_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='investor',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Declined', 'Declined')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_role',
            field=models.CharField(choices=[('founder', 'Founder'), ('co-founder', 'Co-founder'), ('employee', 'Employee')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_month',
            field=models.CharField(choices=[('January', 'January'), ('March', 'March'), ('December', 'December'), ('September', 'September'), ('February', 'February'), ('June', 'June'), ('August', 'August'), ('May', 'May'), ('July', 'July'), ('October', 'October'), ('April', 'April'), ('November', 'November')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_year',
            field=models.CharField(blank=True, choices=[('2003', '2003'), ('2018', '2018'), ('2011', '2011'), ('2008', '2008'), ('2006', '2006'), ('2016', '2016'), ('2004', '2004'), ('2020', '2020'), ('2005', '2005'), ('2019', '2019'), ('2010', '2010'), ('2013', '2013'), ('2017', '2017'), ('2014', '2014'), ('2012', '2012'), ('2021', '2021'), ('2009', '2009'), ('2015', '2015'), ('2007', '2007')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_stage',
            field=models.CharField(choices=[('paying users', 'Paying Users'), ('prototype', 'Prototype'), ('idea', 'Idea'), ('users', 'Users')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Declined', 'Declined')], default='Pending', max_length=100),
        ),
    ]
