# Generated by Django 3.2.7 on 2021-10-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20211009_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='bio',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='investor',
            name='experience',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_type',
            field=models.CharField(choices=[('Venture Capitalist', 'Venture Capitalist'), ('Angel Investor', 'Angel Investor'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='investor',
            name='reason',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='investor',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_bio',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_role',
            field=models.CharField(choices=[('co-founder', 'Co-founder'), ('employee', 'Employee'), ('founder', 'Founder')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='motivation',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_month',
            field=models.CharField(choices=[('October', 'October'), ('June', 'June'), ('May', 'May'), ('March', 'March'), ('November', 'November'), ('January', 'January'), ('April', 'April'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('February', 'February'), ('December', 'December')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_year',
            field=models.CharField(blank=True, choices=[('2019', '2019'), ('2011', '2011'), ('2005', '2005'), ('2009', '2009'), ('2012', '2012'), ('2008', '2008'), ('2020', '2020'), ('2017', '2017'), ('2018', '2018'), ('2003', '2003'), ('2013', '2013'), ('2010', '2010'), ('2015', '2015'), ('2016', '2016'), ('2004', '2004'), ('2006', '2006'), ('2021', '2021'), ('2014', '2014'), ('2007', '2007')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_elevator_pitch',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_pitch',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_stage',
            field=models.CharField(choices=[('prototype', 'Prototype'), ('idea', 'Idea'), ('paying users', 'Paying Users'), ('users', 'Users')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
