# Generated by Django 3.2.7 on 2021-10-10 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20211009_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='applicant_first_name',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='applicant_last_name',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='applicant_phone_no',
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_type',
            field=models.CharField(choices=[('Angel Investor', 'Angel Investor'), ('Venture Capitalist', 'Venture Capitalist'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='investor',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Declined', 'Declined')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_role',
            field=models.CharField(choices=[('founder', 'Founder'), ('co-founder', 'Co-founder'), ('employee', 'Employee')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startup',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_month',
            field=models.CharField(choices=[('September', 'September'), ('April', 'April'), ('August', 'August'), ('March', 'March'), ('October', 'October'), ('February', 'February'), ('July', 'July'), ('November', 'November'), ('December', 'December'), ('January', 'January'), ('May', 'May'), ('June', 'June')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_year',
            field=models.CharField(blank=True, choices=[('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2017', '2017'), ('2013', '2013'), ('2018', '2018'), ('2006', '2006'), ('2012', '2012'), ('2014', '2014'), ('2005', '2005'), ('2021', '2021'), ('2020', '2020'), ('2016', '2016'), ('2008', '2008'), ('2007', '2007'), ('2004', '2004'), ('2019', '2019'), ('2003', '2003'), ('2015', '2015')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Declined', 'Declined')], default='Pending', max_length=100),
        ),
    ]
