# Generated by Django 3.2.7 on 2021-10-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20211010_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='investor_type',
            field=models.CharField(choices=[('Other', 'Other'), ('Venture Capitalist', 'Venture Capitalist'), ('Angel Investor', 'Angel Investor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='investor',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_role',
            field=models.CharField(choices=[('founder', 'Founder'), ('employee', 'Employee'), ('co-founder', 'Co-founder')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_month',
            field=models.CharField(choices=[('April', 'April'), ('September', 'September'), ('December', 'December'), ('March', 'March'), ('November', 'November'), ('January', 'January'), ('August', 'August'), ('February', 'February'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('October', 'October')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_year',
            field=models.CharField(blank=True, choices=[('2013', '2013'), ('2012', '2012'), ('2005', '2005'), ('2021', '2021'), ('2010', '2010'), ('2016', '2016'), ('2007', '2007'), ('2014', '2014'), ('2003', '2003'), ('2020', '2020'), ('2009', '2009'), ('2008', '2008'), ('2011', '2011'), ('2017', '2017'), ('2018', '2018'), ('2006', '2006'), ('2015', '2015'), ('2004', '2004'), ('2019', '2019')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_stage',
            field=models.CharField(choices=[('idea', 'Idea'), ('paying users', 'Paying Users'), ('prototype', 'Prototype'), ('users', 'Users')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
