# Generated by Django 3.2.7 on 2021-10-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20211010_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='investor_type',
            field=models.CharField(choices=[('Angel Investor', 'Angel Investor'), ('Other', 'Other'), ('Venture Capitalist', 'Venture Capitalist')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_role',
            field=models.CharField(choices=[('employee', 'Employee'), ('founder', 'Founder'), ('co-founder', 'Co-founder')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='country',
            field=models.CharField(default='Kenya', max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_month',
            field=models.CharField(choices=[('July', 'July'), ('March', 'March'), ('October', 'October'), ('May', 'May'), ('November', 'November'), ('January', 'January'), ('April', 'April'), ('June', 'June'), ('August', 'August'), ('February', 'February'), ('December', 'December'), ('September', 'September')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2019', '2019'), ('2018', '2018'), ('2012', '2012'), ('2003', '2003'), ('2008', '2008'), ('2020', '2020'), ('2013', '2013'), ('2007', '2007'), ('2004', '2004'), ('2011', '2011'), ('2010', '2010'), ('2005', '2005'), ('2016', '2016'), ('2017', '2017'), ('2015', '2015'), ('2009', '2009'), ('2014', '2014'), ('2006', '2006')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_stage',
            field=models.CharField(choices=[('paying users', 'Paying Users'), ('prototype', 'Prototype'), ('users', 'Users'), ('idea', 'Idea')], max_length=100),
        ),
    ]
