# Generated by Django 3.2.7 on 2021-10-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20211010_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='investor_type',
            field=models.CharField(choices=[('Other', 'Other'), ('Venture Capitalist', 'Venture Capitalist'), ('Angel Investor', 'Angel Investor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='investor',
            name='status',
            field=models.CharField(choices=[('Declined', 'Declined'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='applicant_role',
            field=models.CharField(choices=[('founder', 'Founder'), ('employee', 'Employee'), ('co-founder', 'Co-founder')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_month',
            field=models.CharField(choices=[('October', 'October'), ('August', 'August'), ('June', 'June'), ('December', 'December'), ('September', 'September'), ('February', 'February'), ('July', 'July'), ('May', 'May'), ('March', 'March'), ('April', 'April'), ('January', 'January'), ('November', 'November')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='start_year',
            field=models.CharField(blank=True, choices=[('2004', '2004'), ('2005', '2005'), ('2015', '2015'), ('2009', '2009'), ('2013', '2013'), ('2018', '2018'), ('2006', '2006'), ('2017', '2017'), ('2011', '2011'), ('2008', '2008'), ('2003', '2003'), ('2012', '2012'), ('2016', '2016'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2010', '2010'), ('2014', '2014'), ('2007', '2007')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_stage',
            field=models.CharField(choices=[('idea', 'Idea'), ('users', 'Users'), ('paying users', 'Paying Users'), ('prototype', 'Prototype')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(choices=[('Declined', 'Declined'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=100),
        ),
    ]
